// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations.Ms
{
    [DbContext(typeof(MsDbContext))]
    [Migration("20221008201837_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entities.Concrete.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Core.Entities.Concrete.GroupClaim", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "ClaimId");

                    b.ToTable("GroupClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "tr-TR",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 140, DateTimeKind.Local).AddTicks(9682),
                            IsRemoved = false,
                            Name = "Türkçe",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Code = "en-US",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 143, DateTimeKind.Local).AddTicks(8273),
                            IsRemoved = false,
                            Name = "English",
                            Status = true
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Core.Entities.Concrete.MobileLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSend")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId", "Provider");

                    b.ToTable("MobileLogins");
                });

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Translate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int>("LangId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Translates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Login",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(7617),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Giriş"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Email",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8903),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "E posta"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Password",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8912),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Parola"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Update",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8915),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Güncelle"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Delete",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8919),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Sil"
                        },
                        new
                        {
                            Id = 6,
                            Code = "UsersGroups",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8929),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kullanıcının Grupları"
                        },
                        new
                        {
                            Id = 7,
                            Code = "UsersClaims",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8931),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kullanıcının Yetkileri"
                        },
                        new
                        {
                            Id = 8,
                            Code = "Create",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8933),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yeni"
                        },
                        new
                        {
                            Id = 9,
                            Code = "Users",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8935),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kullanıcılar"
                        },
                        new
                        {
                            Id = 10,
                            Code = "Groups",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8938),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Gruplar"
                        },
                        new
                        {
                            Id = 11,
                            Code = "Login",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8940),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Login"
                        },
                        new
                        {
                            Id = 12,
                            Code = "Email",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8941),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Email"
                        },
                        new
                        {
                            Id = 13,
                            Code = "Password",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8943),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Password"
                        },
                        new
                        {
                            Id = 14,
                            Code = "Update",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8945),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Update"
                        },
                        new
                        {
                            Id = 15,
                            Code = "Delete",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8947),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 16,
                            Code = "UsersGroups",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8948),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "User's Groups"
                        },
                        new
                        {
                            Id = 17,
                            Code = "UsersClaims",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8950),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "User's Claims"
                        },
                        new
                        {
                            Id = 18,
                            Code = "Create",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8953),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Create"
                        },
                        new
                        {
                            Id = 19,
                            Code = "Users",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8955),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Users"
                        },
                        new
                        {
                            Id = 20,
                            Code = "Groups",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8957),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Groups"
                        },
                        new
                        {
                            Id = 21,
                            Code = "OperationClaim",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8959),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Operasyon Yetkileri"
                        },
                        new
                        {
                            Id = 22,
                            Code = "OperationClaim",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8961),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Operation Claim"
                        },
                        new
                        {
                            Id = 23,
                            Code = "Languages",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8962),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Diller"
                        },
                        new
                        {
                            Id = 24,
                            Code = "Languages",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8964),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Languages"
                        },
                        new
                        {
                            Id = 25,
                            Code = "TranslateWords",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8966),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Dil Çevirileri"
                        },
                        new
                        {
                            Id = 26,
                            Code = "TranslateWords",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8968),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Translate Words"
                        },
                        new
                        {
                            Id = 27,
                            Code = "Management",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8969),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yönetim"
                        },
                        new
                        {
                            Id = 28,
                            Code = "Management",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8971),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Management"
                        },
                        new
                        {
                            Id = 29,
                            Code = "AppMenu",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8973),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Uygulama"
                        },
                        new
                        {
                            Id = 30,
                            Code = "AppMenu",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8975),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Application"
                        },
                        new
                        {
                            Id = 31,
                            Code = "Added",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8977),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Başarıyla Eklendi."
                        },
                        new
                        {
                            Id = 32,
                            Code = "Added",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8979),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Successfully Added."
                        },
                        new
                        {
                            Id = 33,
                            Code = "Updated",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(8981),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Başarıyla Güncellendi."
                        },
                        new
                        {
                            Id = 34,
                            Code = "Updated",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9062),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Successfully Updated."
                        },
                        new
                        {
                            Id = 35,
                            Code = "Deleted",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9064),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Başarıyla Silindi."
                        },
                        new
                        {
                            Id = 36,
                            Code = "Deleted",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9066),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Successfully Deleted."
                        },
                        new
                        {
                            Id = 37,
                            Code = "OperationClaimExists",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9068),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Bu operasyon izni zaten mevcut."
                        },
                        new
                        {
                            Id = 38,
                            Code = "OperationClaimExists",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9070),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "This operation permit already exists."
                        },
                        new
                        {
                            Id = 39,
                            Code = "StringLengthMustBeGreaterThanThree",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9072),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Lütfen En Az 3 Karakterden Oluşan Bir İfade Girin."
                        },
                        new
                        {
                            Id = 40,
                            Code = "StringLengthMustBeGreaterThanThree",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9074),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Please Enter A Phrase Of At Least 3 Characters."
                        },
                        new
                        {
                            Id = 41,
                            Code = "CouldNotBeVerifyCid",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9075),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kimlik No Doğrulanamadı."
                        },
                        new
                        {
                            Id = 42,
                            Code = "CouldNotBeVerifyCid",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9077),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Could not be verify Citizen Id"
                        },
                        new
                        {
                            Id = 43,
                            Code = "VerifyCid",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9079),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kimlik No Doğrulandı."
                        },
                        new
                        {
                            Id = 44,
                            Code = "VerifyCid",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9081),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Verify Citizen Id"
                        },
                        new
                        {
                            Id = 45,
                            Code = "AuthorizationsDenied",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9084),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yetkiniz olmayan bir alana girmeye çalıştığınız tespit edildi."
                        },
                        new
                        {
                            Id = 46,
                            Code = "AuthorizationsDenied",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9086),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "It has been detected that you are trying to enter an area that you do not have authorization."
                        },
                        new
                        {
                            Id = 47,
                            Code = "UserNotFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9087),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kimlik Bilgileri Doğrulanamadı. Lütfen Yeni Kayıt Ekranını kullanın."
                        },
                        new
                        {
                            Id = 48,
                            Code = "UserNotFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9089),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Credentials Could Not Verify. Please use the New Registration Screen."
                        },
                        new
                        {
                            Id = 49,
                            Code = "PasswordError",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9091),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kimlik Bilgileri Doğrulanamadı, Kullanıcı adı ve/veya parola hatalı."
                        },
                        new
                        {
                            Id = 50,
                            Code = "PasswordError",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9095),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Credentials Failed to Authenticate, Username and / or password incorrect."
                        },
                        new
                        {
                            Id = 51,
                            Code = "SuccessfulLogin",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9097),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Sisteme giriş başarılı."
                        },
                        new
                        {
                            Id = 52,
                            Code = "SuccessfulLogin",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9099),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Login to the system is successful."
                        },
                        new
                        {
                            Id = 53,
                            Code = "SendMobileCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9100),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Lütfen Size SMS Olarak Gönderilen Kodu Girin!"
                        },
                        new
                        {
                            Id = 54,
                            Code = "SendMobileCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9102),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Please Enter The Code Sent To You By SMS!"
                        },
                        new
                        {
                            Id = 55,
                            Code = "NameAlreadyExist",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9104),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Oluşturmaya Çalıştığınız Nesne Zaten Var."
                        },
                        new
                        {
                            Id = 56,
                            Code = "NameAlreadyExist",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9106),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "The Object You Are Trying To Create Already Exists."
                        },
                        new
                        {
                            Id = 57,
                            Code = "WrongCID",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9107),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Vatandaşlık No Sistemimizde Bulunamadı. Lütfen Yeni Kayıt Oluşturun!"
                        },
                        new
                        {
                            Id = 58,
                            Code = "WrongCID",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9109),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Citizenship Number Not Found In Our System. Please Create New Registration!"
                        },
                        new
                        {
                            Id = 59,
                            Code = "CID",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9111),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Vatandaşlık No"
                        },
                        new
                        {
                            Id = 60,
                            Code = "CID",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9113),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Citizenship Number"
                        },
                        new
                        {
                            Id = 61,
                            Code = "PasswordEmpty",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9114),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Parola boş olamaz!"
                        },
                        new
                        {
                            Id = 62,
                            Code = "PasswordEmpty",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9116),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Password can not be empty!"
                        },
                        new
                        {
                            Id = 63,
                            Code = "PasswordLength",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9118),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Minimum 8 Karakter Uzunluğunda Olmalıdır!"
                        },
                        new
                        {
                            Id = 64,
                            Code = "PasswordLength",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9120),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Must be at least 8 characters long! "
                        },
                        new
                        {
                            Id = 65,
                            Code = "PasswordUppercaseLetter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9122),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "En Az 1 Büyük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = 66,
                            Code = "PasswordUppercaseLetter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9125),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Must Contain At Least 1 Capital Letter!"
                        },
                        new
                        {
                            Id = 67,
                            Code = "PasswordLowercaseLetter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9127),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "En Az 1 Küçük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = 68,
                            Code = "PasswordLowercaseLetter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9129),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Must Contain At Least 1 Lowercase Letter!"
                        },
                        new
                        {
                            Id = 69,
                            Code = "PasswordDigit",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9131),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "En Az 1 Rakam İçermelidir!"
                        },
                        new
                        {
                            Id = 70,
                            Code = "PasswordDigit",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9133),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "It Must Contain At Least 1 Digit!"
                        },
                        new
                        {
                            Id = 71,
                            Code = "PasswordSpecialCharacter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9135),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "En Az 1 Simge İçermelidir!"
                        },
                        new
                        {
                            Id = 72,
                            Code = "PasswordSpecialCharacter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9136),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Must Contain At Least 1 Symbol!"
                        },
                        new
                        {
                            Id = 73,
                            Code = "SendPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9138),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yeni Parolanız E-Posta Adresinize Gönderildi."
                        },
                        new
                        {
                            Id = 74,
                            Code = "SendPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9140),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Your new password has been sent to your e-mail address."
                        },
                        new
                        {
                            Id = 75,
                            Code = "InvalidCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9142),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Geçersiz Bir Kod Girdiniz!"
                        },
                        new
                        {
                            Id = 76,
                            Code = "InvalidCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9144),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "You Entered An Invalid Code!"
                        },
                        new
                        {
                            Id = 77,
                            Code = "SmsServiceNotFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9145),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "SMS Servisine Ulaşılamıyor."
                        },
                        new
                        {
                            Id = 78,
                            Code = "SmsServiceNotFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9147),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Unable to Reach SMS Service."
                        },
                        new
                        {
                            Id = 79,
                            Code = "TrueButCellPhone",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9149),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Bilgiler doğru. Cep telefonu gerekiyor."
                        },
                        new
                        {
                            Id = 80,
                            Code = "TrueButCellPhone",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9151),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "The information is correct. Cell phone is required."
                        },
                        new
                        {
                            Id = 81,
                            Code = "TokenProviderException",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9152),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Token Provider boş olamaz!"
                        },
                        new
                        {
                            Id = 82,
                            Code = "TokenProviderException",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9154),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Token Provider cannot be empty!"
                        },
                        new
                        {
                            Id = 83,
                            Code = "Unknown",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9156),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Bilinmiyor!"
                        },
                        new
                        {
                            Id = 84,
                            Code = "Unknown",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9158),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Unknown!"
                        },
                        new
                        {
                            Id = 85,
                            Code = "NewPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9159),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yeni Parola:"
                        },
                        new
                        {
                            Id = 86,
                            Code = "NewPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9161),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "New Password:"
                        },
                        new
                        {
                            Id = 87,
                            Code = "ChangePassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9163),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Parola Değiştir"
                        },
                        new
                        {
                            Id = 88,
                            Code = "ChangePassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9165),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Change Password"
                        },
                        new
                        {
                            Id = 89,
                            Code = "Save",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9166),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = 90,
                            Code = "Save",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9168),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Save"
                        },
                        new
                        {
                            Id = 91,
                            Code = "GroupName",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9170),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Grup Adı"
                        },
                        new
                        {
                            Id = 92,
                            Code = "GroupName",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9172),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Group Name"
                        },
                        new
                        {
                            Id = 93,
                            Code = "FullName",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9173),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Tam Adı"
                        },
                        new
                        {
                            Id = 94,
                            Code = "FullName",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9211),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Full Name"
                        },
                        new
                        {
                            Id = 95,
                            Code = "Address",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9213),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Adres"
                        },
                        new
                        {
                            Id = 96,
                            Code = "Address",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9215),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Address"
                        },
                        new
                        {
                            Id = 97,
                            Code = "Notes",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9217),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Notlar"
                        },
                        new
                        {
                            Id = 98,
                            Code = "Notes",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9219),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Notes"
                        },
                        new
                        {
                            Id = 99,
                            Code = "ConfirmPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9221),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Parolayı Doğrula"
                        },
                        new
                        {
                            Id = 100,
                            Code = "ConfirmPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9222),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Confirm Password"
                        },
                        new
                        {
                            Id = 101,
                            Code = "Code",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9224),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kod"
                        },
                        new
                        {
                            Id = 102,
                            Code = "Code",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9226),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Code"
                        },
                        new
                        {
                            Id = 103,
                            Code = "Alias",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9228),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Görünen Ad"
                        },
                        new
                        {
                            Id = 104,
                            Code = "Alias",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9230),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Alias"
                        },
                        new
                        {
                            Id = 105,
                            Code = "Description",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9232),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Açıklama"
                        },
                        new
                        {
                            Id = 106,
                            Code = "Description",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9234),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Description"
                        },
                        new
                        {
                            Id = 107,
                            Code = "Value",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9235),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Değer"
                        },
                        new
                        {
                            Id = 108,
                            Code = "Value",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9239),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Value"
                        },
                        new
                        {
                            Id = 109,
                            Code = "LangCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9240),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Dil Kodu"
                        },
                        new
                        {
                            Id = 110,
                            Code = "LangCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9242),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Lang Code"
                        },
                        new
                        {
                            Id = 111,
                            Code = "Name",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9244),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Adı"
                        },
                        new
                        {
                            Id = 112,
                            Code = "Name",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9246),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Name"
                        },
                        new
                        {
                            Id = 113,
                            Code = "MobilePhones",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9247),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Cep Telefonu"
                        },
                        new
                        {
                            Id = 114,
                            Code = "MobilePhones",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9249),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Mobile Phone"
                        },
                        new
                        {
                            Id = 115,
                            Code = "NoRecordsFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9251),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kayıt Bulunamadı"
                        },
                        new
                        {
                            Id = 116,
                            Code = "NoRecordsFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9253),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "No Records Found"
                        },
                        new
                        {
                            Id = 117,
                            Code = "Required",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9255),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Bu alan zorunludur!"
                        },
                        new
                        {
                            Id = 118,
                            Code = "Required",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9256),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "This field is required!"
                        },
                        new
                        {
                            Id = 119,
                            Code = "Permissions",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9258),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Permissions"
                        },
                        new
                        {
                            Id = 120,
                            Code = "Permissions",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9260),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "İzinler"
                        },
                        new
                        {
                            Id = 121,
                            Code = "GroupList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9262),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Grup Listesi"
                        },
                        new
                        {
                            Id = 122,
                            Code = "GroupList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9263),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Group List"
                        },
                        new
                        {
                            Id = 123,
                            Code = "GrupPermissions",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9265),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Grup Yetkileri"
                        },
                        new
                        {
                            Id = 124,
                            Code = "GrupPermissions",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9267),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Grup Permissions"
                        },
                        new
                        {
                            Id = 125,
                            Code = "Add",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9269),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 126,
                            Code = "Add",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9271),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 127,
                            Code = "UserList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9273),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kullanıcı Listesi"
                        },
                        new
                        {
                            Id = 128,
                            Code = "UserList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9274),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "User List"
                        },
                        new
                        {
                            Id = 129,
                            Code = "OperationClaimList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9276),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yetki Listesi"
                        },
                        new
                        {
                            Id = 130,
                            Code = "OperationClaimList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9280),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "OperationClaim List"
                        },
                        new
                        {
                            Id = 131,
                            Code = "LanguageList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9282),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Dil Listesi"
                        },
                        new
                        {
                            Id = 132,
                            Code = "LanguageList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9284),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Language List"
                        },
                        new
                        {
                            Id = 133,
                            Code = "TranslateList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9285),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Dil Çeviri Listesi"
                        },
                        new
                        {
                            Id = 134,
                            Code = "TranslateList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9287),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Translate List"
                        },
                        new
                        {
                            Id = 135,
                            Code = "LogList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9289),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "İşlem Kütüğü"
                        },
                        new
                        {
                            Id = 136,
                            Code = "LogList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9291),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "LogList"
                        },
                        new
                        {
                            Id = 137,
                            Code = "DeleteConfirm",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9292),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Emin misiniz?"
                        },
                        new
                        {
                            Id = 138,
                            Code = "DeleteConfirm",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 18, 37, 155, DateTimeKind.Local).AddTicks(9294),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Are you sure?"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CitizenId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("MobilePhones")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateContactDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("MobilePhones");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserClaim", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Entities.Concrete.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Entities.Concrete.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUser")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NeighbourhoodId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("Entities.Concrete.Personnel", b =>
                {
                    b.HasOne("Entities.Concrete.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
