// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations.Ms
{
    [DbContext(typeof(MsDbContext))]
    partial class MsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entities.Concrete.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Core.Entities.Concrete.GroupClaim", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "ClaimId");

                    b.ToTable("GroupClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "tr-TR",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 269, DateTimeKind.Local).AddTicks(2390),
                            IsRemoved = false,
                            Name = "Türkçe",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Code = "en-US",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 270, DateTimeKind.Local).AddTicks(3796),
                            IsRemoved = false,
                            Name = "English",
                            Status = true
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Core.Entities.Concrete.MobileLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSend")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId", "Provider");

                    b.ToTable("MobileLogins");
                });

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Translate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int>("LangId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Translates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Login",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(6738),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Giriş"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Email",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(7985),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "E posta"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Password",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(7993),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Parola"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Update",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(7995),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Güncelle"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Delete",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(7998),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Sil"
                        },
                        new
                        {
                            Id = 6,
                            Code = "UsersGroups",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8155),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kullanıcının Grupları"
                        },
                        new
                        {
                            Id = 7,
                            Code = "UsersClaims",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8157),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kullanıcının Yetkileri"
                        },
                        new
                        {
                            Id = 8,
                            Code = "Create",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8159),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yeni"
                        },
                        new
                        {
                            Id = 9,
                            Code = "Users",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8161),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kullanıcılar"
                        },
                        new
                        {
                            Id = 10,
                            Code = "Groups",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8165),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Gruplar"
                        },
                        new
                        {
                            Id = 11,
                            Code = "Login",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8167),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Login"
                        },
                        new
                        {
                            Id = 12,
                            Code = "Email",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8169),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Email"
                        },
                        new
                        {
                            Id = 13,
                            Code = "Password",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8170),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Password"
                        },
                        new
                        {
                            Id = 14,
                            Code = "Update",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8172),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Update"
                        },
                        new
                        {
                            Id = 15,
                            Code = "Delete",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8174),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 16,
                            Code = "UsersGroups",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8175),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "User's Groups"
                        },
                        new
                        {
                            Id = 17,
                            Code = "UsersClaims",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8177),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "User's Claims"
                        },
                        new
                        {
                            Id = 18,
                            Code = "Create",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8180),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Create"
                        },
                        new
                        {
                            Id = 19,
                            Code = "Users",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8182),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Users"
                        },
                        new
                        {
                            Id = 20,
                            Code = "Groups",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8183),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Groups"
                        },
                        new
                        {
                            Id = 21,
                            Code = "OperationClaim",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8185),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Operasyon Yetkileri"
                        },
                        new
                        {
                            Id = 22,
                            Code = "OperationClaim",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8187),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Operation Claim"
                        },
                        new
                        {
                            Id = 23,
                            Code = "Languages",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8188),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Diller"
                        },
                        new
                        {
                            Id = 24,
                            Code = "Languages",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8190),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Languages"
                        },
                        new
                        {
                            Id = 25,
                            Code = "TranslateWords",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8192),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Dil Çevirileri"
                        },
                        new
                        {
                            Id = 26,
                            Code = "TranslateWords",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8194),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Translate Words"
                        },
                        new
                        {
                            Id = 27,
                            Code = "Management",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8195),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yönetim"
                        },
                        new
                        {
                            Id = 28,
                            Code = "Management",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8197),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Management"
                        },
                        new
                        {
                            Id = 29,
                            Code = "AppMenu",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8199),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Uygulama"
                        },
                        new
                        {
                            Id = 30,
                            Code = "AppMenu",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8200),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Application"
                        },
                        new
                        {
                            Id = 31,
                            Code = "Added",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8202),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Başarıyla Eklendi."
                        },
                        new
                        {
                            Id = 32,
                            Code = "Added",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8204),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Successfully Added."
                        },
                        new
                        {
                            Id = 33,
                            Code = "Updated",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8205),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Başarıyla Güncellendi."
                        },
                        new
                        {
                            Id = 34,
                            Code = "Updated",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8208),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Successfully Updated."
                        },
                        new
                        {
                            Id = 35,
                            Code = "Deleted",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8210),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Başarıyla Silindi."
                        },
                        new
                        {
                            Id = 36,
                            Code = "Deleted",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8212),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Successfully Deleted."
                        },
                        new
                        {
                            Id = 37,
                            Code = "OperationClaimExists",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8213),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Bu operasyon izni zaten mevcut."
                        },
                        new
                        {
                            Id = 38,
                            Code = "OperationClaimExists",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8215),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "This operation permit already exists."
                        },
                        new
                        {
                            Id = 39,
                            Code = "StringLengthMustBeGreaterThanThree",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8217),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Lütfen En Az 3 Karakterden Oluşan Bir İfade Girin."
                        },
                        new
                        {
                            Id = 40,
                            Code = "StringLengthMustBeGreaterThanThree",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8219),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Please Enter A Phrase Of At Least 3 Characters."
                        },
                        new
                        {
                            Id = 41,
                            Code = "CouldNotBeVerifyCid",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8221),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kimlik No Doğrulanamadı."
                        },
                        new
                        {
                            Id = 42,
                            Code = "CouldNotBeVerifyCid",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8223),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Could not be verify Citizen Id"
                        },
                        new
                        {
                            Id = 43,
                            Code = "VerifyCid",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8225),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kimlik No Doğrulandı."
                        },
                        new
                        {
                            Id = 44,
                            Code = "VerifyCid",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8226),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Verify Citizen Id"
                        },
                        new
                        {
                            Id = 45,
                            Code = "AuthorizationsDenied",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8228),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yetkiniz olmayan bir alana girmeye çalıştığınız tespit edildi."
                        },
                        new
                        {
                            Id = 46,
                            Code = "AuthorizationsDenied",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8230),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "It has been detected that you are trying to enter an area that you do not have authorization."
                        },
                        new
                        {
                            Id = 47,
                            Code = "UserNotFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8232),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kimlik Bilgileri Doğrulanamadı. Lütfen Yeni Kayıt Ekranını kullanın."
                        },
                        new
                        {
                            Id = 48,
                            Code = "UserNotFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8233),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Credentials Could Not Verify. Please use the New Registration Screen."
                        },
                        new
                        {
                            Id = 49,
                            Code = "PasswordError",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8235),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kimlik Bilgileri Doğrulanamadı, Kullanıcı adı ve/veya parola hatalı."
                        },
                        new
                        {
                            Id = 50,
                            Code = "PasswordError",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8237),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Credentials Failed to Authenticate, Username and / or password incorrect."
                        },
                        new
                        {
                            Id = 51,
                            Code = "SuccessfulLogin",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8238),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Sisteme giriş başarılı."
                        },
                        new
                        {
                            Id = 52,
                            Code = "SuccessfulLogin",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8240),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Login to the system is successful."
                        },
                        new
                        {
                            Id = 53,
                            Code = "SendMobileCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8242),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Lütfen Size SMS Olarak Gönderilen Kodu Girin!"
                        },
                        new
                        {
                            Id = 54,
                            Code = "SendMobileCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8243),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Please Enter The Code Sent To You By SMS!"
                        },
                        new
                        {
                            Id = 55,
                            Code = "NameAlreadyExist",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8245),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Oluşturmaya Çalıştığınız Nesne Zaten Var."
                        },
                        new
                        {
                            Id = 56,
                            Code = "NameAlreadyExist",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8247),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "The Object You Are Trying To Create Already Exists."
                        },
                        new
                        {
                            Id = 57,
                            Code = "WrongCID",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8248),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Vatandaşlık No Sistemimizde Bulunamadı. Lütfen Yeni Kayıt Oluşturun!"
                        },
                        new
                        {
                            Id = 58,
                            Code = "WrongCID",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8250),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Citizenship Number Not Found In Our System. Please Create New Registration!"
                        },
                        new
                        {
                            Id = 59,
                            Code = "CID",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8252),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Vatandaşlık No"
                        },
                        new
                        {
                            Id = 60,
                            Code = "CID",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8253),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Citizenship Number"
                        },
                        new
                        {
                            Id = 61,
                            Code = "PasswordEmpty",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8255),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Parola boş olamaz!"
                        },
                        new
                        {
                            Id = 62,
                            Code = "PasswordEmpty",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8257),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Password can not be empty!"
                        },
                        new
                        {
                            Id = 63,
                            Code = "PasswordLength",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8259),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Minimum 8 Karakter Uzunluğunda Olmalıdır!"
                        },
                        new
                        {
                            Id = 64,
                            Code = "PasswordLength",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8260),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Must be at least 8 characters long! "
                        },
                        new
                        {
                            Id = 65,
                            Code = "PasswordUppercaseLetter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8262),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "En Az 1 Büyük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = 66,
                            Code = "PasswordUppercaseLetter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8302),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Must Contain At Least 1 Capital Letter!"
                        },
                        new
                        {
                            Id = 67,
                            Code = "PasswordLowercaseLetter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8304),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "En Az 1 Küçük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = 68,
                            Code = "PasswordLowercaseLetter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8306),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Must Contain At Least 1 Lowercase Letter!"
                        },
                        new
                        {
                            Id = 69,
                            Code = "PasswordDigit",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8307),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "En Az 1 Rakam İçermelidir!"
                        },
                        new
                        {
                            Id = 70,
                            Code = "PasswordDigit",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8309),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "It Must Contain At Least 1 Digit!"
                        },
                        new
                        {
                            Id = 71,
                            Code = "PasswordSpecialCharacter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8311),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "En Az 1 Simge İçermelidir!"
                        },
                        new
                        {
                            Id = 72,
                            Code = "PasswordSpecialCharacter",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8313),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Must Contain At Least 1 Symbol!"
                        },
                        new
                        {
                            Id = 73,
                            Code = "SendPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8314),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yeni Parolanız E-Posta Adresinize Gönderildi."
                        },
                        new
                        {
                            Id = 74,
                            Code = "SendPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8316),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Your new password has been sent to your e-mail address."
                        },
                        new
                        {
                            Id = 75,
                            Code = "InvalidCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8318),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Geçersiz Bir Kod Girdiniz!"
                        },
                        new
                        {
                            Id = 76,
                            Code = "InvalidCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8319),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "You Entered An Invalid Code!"
                        },
                        new
                        {
                            Id = 77,
                            Code = "SmsServiceNotFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8321),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "SMS Servisine Ulaşılamıyor."
                        },
                        new
                        {
                            Id = 78,
                            Code = "SmsServiceNotFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8323),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Unable to Reach SMS Service."
                        },
                        new
                        {
                            Id = 79,
                            Code = "TrueButCellPhone",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8325),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Bilgiler doğru. Cep telefonu gerekiyor."
                        },
                        new
                        {
                            Id = 80,
                            Code = "TrueButCellPhone",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8327),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "The information is correct. Cell phone is required."
                        },
                        new
                        {
                            Id = 81,
                            Code = "TokenProviderException",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8328),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Token Provider boş olamaz!"
                        },
                        new
                        {
                            Id = 82,
                            Code = "TokenProviderException",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8330),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Token Provider cannot be empty!"
                        },
                        new
                        {
                            Id = 83,
                            Code = "Unknown",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8332),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Bilinmiyor!"
                        },
                        new
                        {
                            Id = 84,
                            Code = "Unknown",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8333),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Unknown!"
                        },
                        new
                        {
                            Id = 85,
                            Code = "NewPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8335),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yeni Parola:"
                        },
                        new
                        {
                            Id = 86,
                            Code = "NewPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8337),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "New Password:"
                        },
                        new
                        {
                            Id = 87,
                            Code = "ChangePassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8338),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Parola Değiştir"
                        },
                        new
                        {
                            Id = 88,
                            Code = "ChangePassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8340),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Change Password"
                        },
                        new
                        {
                            Id = 89,
                            Code = "Save",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8342),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = 90,
                            Code = "Save",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8343),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Save"
                        },
                        new
                        {
                            Id = 91,
                            Code = "GroupName",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8346),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Grup Adı"
                        },
                        new
                        {
                            Id = 92,
                            Code = "GroupName",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8347),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Group Name"
                        },
                        new
                        {
                            Id = 93,
                            Code = "FullName",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8349),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Tam Adı"
                        },
                        new
                        {
                            Id = 94,
                            Code = "FullName",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8351),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Full Name"
                        },
                        new
                        {
                            Id = 95,
                            Code = "Address",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8352),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Adres"
                        },
                        new
                        {
                            Id = 96,
                            Code = "Address",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8354),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Address"
                        },
                        new
                        {
                            Id = 97,
                            Code = "Notes",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8356),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Notlar"
                        },
                        new
                        {
                            Id = 98,
                            Code = "Notes",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8357),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Notes"
                        },
                        new
                        {
                            Id = 99,
                            Code = "ConfirmPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8359),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Parolayı Doğrula"
                        },
                        new
                        {
                            Id = 100,
                            Code = "ConfirmPassword",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8361),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Confirm Password"
                        },
                        new
                        {
                            Id = 101,
                            Code = "Code",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8362),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kod"
                        },
                        new
                        {
                            Id = 102,
                            Code = "Code",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8364),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Code"
                        },
                        new
                        {
                            Id = 103,
                            Code = "Alias",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8366),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Görünen Ad"
                        },
                        new
                        {
                            Id = 104,
                            Code = "Alias",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8367),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Alias"
                        },
                        new
                        {
                            Id = 105,
                            Code = "Description",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8369),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Açıklama"
                        },
                        new
                        {
                            Id = 106,
                            Code = "Description",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8371),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Description"
                        },
                        new
                        {
                            Id = 107,
                            Code = "Value",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8372),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Değer"
                        },
                        new
                        {
                            Id = 108,
                            Code = "Value",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8375),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Value"
                        },
                        new
                        {
                            Id = 109,
                            Code = "LangCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8377),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Dil Kodu"
                        },
                        new
                        {
                            Id = 110,
                            Code = "LangCode",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8378),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Lang Code"
                        },
                        new
                        {
                            Id = 111,
                            Code = "Name",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8380),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Adı"
                        },
                        new
                        {
                            Id = 112,
                            Code = "Name",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8382),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Name"
                        },
                        new
                        {
                            Id = 113,
                            Code = "MobilePhones",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8383),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Cep Telefonu"
                        },
                        new
                        {
                            Id = 114,
                            Code = "MobilePhones",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8385),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Mobile Phone"
                        },
                        new
                        {
                            Id = 115,
                            Code = "NoRecordsFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8387),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kayıt Bulunamadı"
                        },
                        new
                        {
                            Id = 116,
                            Code = "NoRecordsFound",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8388),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "No Records Found"
                        },
                        new
                        {
                            Id = 117,
                            Code = "Required",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8390),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Bu alan zorunludur!"
                        },
                        new
                        {
                            Id = 118,
                            Code = "Required",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8392),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "This field is required!"
                        },
                        new
                        {
                            Id = 119,
                            Code = "Permissions",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8393),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Permissions"
                        },
                        new
                        {
                            Id = 120,
                            Code = "Permissions",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8395),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "İzinler"
                        },
                        new
                        {
                            Id = 121,
                            Code = "GroupList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8397),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Grup Listesi"
                        },
                        new
                        {
                            Id = 122,
                            Code = "GroupList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8398),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Group List"
                        },
                        new
                        {
                            Id = 123,
                            Code = "GrupPermissions",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8400),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Grup Yetkileri"
                        },
                        new
                        {
                            Id = 124,
                            Code = "GrupPermissions",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8402),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Grup Permissions"
                        },
                        new
                        {
                            Id = 125,
                            Code = "Add",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8403),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 126,
                            Code = "Add",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8405),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 127,
                            Code = "UserList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8407),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Kullanıcı Listesi"
                        },
                        new
                        {
                            Id = 128,
                            Code = "UserList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8409),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "User List"
                        },
                        new
                        {
                            Id = 129,
                            Code = "OperationClaimList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8410),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Yetki Listesi"
                        },
                        new
                        {
                            Id = 130,
                            Code = "OperationClaimList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8451),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "OperationClaim List"
                        },
                        new
                        {
                            Id = 131,
                            Code = "LanguageList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8453),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Dil Listesi"
                        },
                        new
                        {
                            Id = 132,
                            Code = "LanguageList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8454),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Language List"
                        },
                        new
                        {
                            Id = 133,
                            Code = "TranslateList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8456),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Dil Çeviri Listesi"
                        },
                        new
                        {
                            Id = 134,
                            Code = "TranslateList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8458),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Translate List"
                        },
                        new
                        {
                            Id = 135,
                            Code = "LogList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8459),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "İşlem Kütüğü"
                        },
                        new
                        {
                            Id = 136,
                            Code = "LogList",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8461),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "LogList"
                        },
                        new
                        {
                            Id = 137,
                            Code = "DeleteConfirm",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8463),
                            IsRemoved = false,
                            LangId = 1,
                            Status = true,
                            Value = "Emin misiniz?"
                        },
                        new
                        {
                            Id = 138,
                            Code = "DeleteConfirm",
                            CreatedBy = 0,
                            CreationDate = new DateTime(2022, 10, 8, 23, 43, 53, 284, DateTimeKind.Local).AddTicks(8464),
                            IsRemoved = false,
                            LangId = 2,
                            Status = true,
                            Value = "Are you sure?"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CitizenId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("MobilePhones")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateContactDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("MobilePhones");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserClaim", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Entities.Concrete.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Entities.Concrete.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<int?>("CountyId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUser")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NeighbourhoodId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RemovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("Entities.Concrete.Personnel", b =>
                {
                    b.HasOne("Entities.Concrete.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
